// <auto-generated />
using System;
using GeoCommand.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoCommand.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GeoCommandDbContext))]
    partial class GeoCommandDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoCommand.Domain.Events.GeoEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("location");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)")
                        .HasColumnName("message");

                    b.Property<Guid?>("MissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("mission_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_events_occurred_at_utc");

                    b.HasIndex("VehicleId", "OccurredAtUtc")
                        .HasDatabaseName("ix_events_vehicle_id_occurred_at_utc");

                    b.HasIndex("VehicleId", "ZoneId", "Type", "OccurredAtUtc")
                        .IsUnique()
                        .HasDatabaseName("ix_events_zone_transition_unique")
                        .HasFilter("zone_id IS NOT NULL");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("GeoCommand.Domain.Missions.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_missions");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("ix_missions_one_active_per_vehicle")
                        .HasFilter("status IN ('Assigned', 'InProgress')");

                    b.HasIndex("VehicleId", "AssignedAtUtc")
                        .HasDatabaseName("ix_missions_vehicle_id_assigned_at_utc");

                    b.ToTable("missions", (string)null);
                });

            modelBuilder.Entity("GeoCommand.Domain.Vehicles.PositionRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<double>("HeadingDegrees")
                        .HasColumnType("double precision")
                        .HasColumnName("heading_degrees");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source");

                    b.Property<double>("SpeedMps")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_mps");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_position_records");

                    b.HasIndex("VehicleId", "RecordedAtUtc")
                        .HasDatabaseName("ix_position_records_vehicle_id_recorded_at_utc");

                    b.ToTable("position_records", (string)null);
                });

            modelBuilder.Entity("GeoCommand.Domain.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveMissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_mission_id");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("callsign");

                    b.Property<double>("LastHeadingDegrees")
                        .HasColumnType("double precision")
                        .HasColumnName("last_heading_degrees");

                    b.Property<Point>("LastPosition")
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("last_position");

                    b.Property<double>("LastSpeedMps")
                        .HasColumnType("double precision")
                        .HasColumnName("last_speed_mps");

                    b.Property<DateTimeOffset?>("LastUpdateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("Callsign")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_callsign");

                    b.HasIndex("LastPosition")
                        .HasDatabaseName("ix_vehicles_last_position");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LastPosition"), "gist");

                    b.ToTable("vehicles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f1c7a52-6a3e-4c1e-9d11-0000000000a1"),
                            Callsign = "ALFA-1",
                            LastHeadingDegrees = 0.0,
                            LastSpeedMps = 0.0,
                            Status = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("0f1c7a52-6a3e-4c1e-9d11-0000000000b2"),
                            Callsign = "BRAVO-2",
                            LastHeadingDegrees = 0.0,
                            LastSpeedMps = 0.0,
                            Status = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("0f1c7a52-6a3e-4c1e-9d11-0000000000c3"),
                            Callsign = "CHARLIE-3",
                            LastHeadingDegrees = 0.0,
                            LastSpeedMps = 0.0,
                            Status = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("0f1c7a52-6a3e-4c1e-9d11-0000000000d4"),
                            Callsign = "DELTA-4",
                            LastHeadingDegrees = 0.0,
                            LastSpeedMps = 0.0,
                            Status = "Unknown"
                        });
                });

            modelBuilder.Entity("GeoCommand.Domain.Zones.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Polygon>("Area")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon,4326)")
                        .HasColumnName("area");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_zones");

                    b.HasIndex("Area")
                        .HasDatabaseName("ix_zones_area");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Area"), "gist");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("GeoCommand.Domain.Zones.ZoneMembership", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.Property<DateTimeOffset>("EnteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entered_at_utc");

                    b.HasKey("VehicleId", "ZoneId")
                        .HasName("pk_zone_memberships");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_zone_memberships_zone_id");

                    b.ToTable("zone_memberships", (string)null);
                });

            modelBuilder.Entity("GeoCommand.Domain.Events.GeoEvent", b =>
                {
                    b.HasOne("GeoCommand.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_events_vehicles_vehicle_id");
                });

            modelBuilder.Entity("GeoCommand.Domain.Missions.Mission", b =>
                {
                    b.HasOne("GeoCommand.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_missions_vehicles_vehicle_id");
                });

            modelBuilder.Entity("GeoCommand.Domain.Vehicles.PositionRecord", b =>
                {
                    b.HasOne("GeoCommand.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_position_records_vehicles_vehicle_id");
                });

            modelBuilder.Entity("GeoCommand.Domain.Zones.ZoneMembership", b =>
                {
                    b.HasOne("GeoCommand.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zone_memberships_vehicles_vehicle_id");

                    b.HasOne("GeoCommand.Domain.Zones.Zone", null)
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zone_memberships_zones_zone_id");
                });
#pragma warning restore 612, 618
        }
    }
}
